apiVersion: v1
kind: Secret
metadata:
  name: secret-github
  namespace: tekton-pipelines
  annotations:
    tekton.dev/git-0: YOUR_GIT_SERVER
type: kubernetes.io/basic-auth
stringData:
  username: foo
  password: YOUR_TOKEN_HERE

---

apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: tekton-pipelines
type: Opaque
stringData:
  token: YOUR_TOKEN_HERE

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: simple-pipeline-user-binding
  namespace: tekton-pipelines
spec:
  params:
  - name: github_host_url
    value: "YOUR_GIT_SERVER_NO_PROTOCOL"
  - name: api_path_prefix
    value: "YOUR_API_PATH_PREFIX"